# Generated by Django 2.1.5 on 2019-02-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_auto_20181228_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='resWatsonScore',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='resWatsonClase',
            new_name='url',
        ),
    ]
