# Generated by Django 2.1.5 on 2019-02-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0008_auto_20190204_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='desc',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='label',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='text',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
