# Generated by Django 2.1.5 on 2019-02-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0010_document_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='catLabel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
