# Generated by Django 2.1.5 on 2019-02-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0011_document_catlabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='conRel',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='conSource',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='conText',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
