# Generated by Django 2.1.5 on 2019-02-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0012_auto_20190206_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='entityText',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='entityType',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
